site_name: My Code Library
theme:
  name: material
  palette: 
    scheme: slate # Dark mode is usually better for code
  features:
    - content.code.copy
    - navigation.expand

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - CLI Libraries:
      - Azure CLI: azcli.md
      - OpenSSL: openssl.md
  - Version Control:
      - Git: git.md
  - Terraform:
      - Import: terraform/import.md
      - Init: terraform/init.md
      - Plan/Apply: terraform/planapply.md
      - Tfstate: terraform/tfstate.md
      - Console: terraform/console.md
      - MV: terraform/mv.md
  - Kubernetes:
      - AKS: kubernetes/aks.md
      - Exec with Kubectl: kubernetes/kubectlexec.md